enum ClientHeaders {
  ping,
  accessAccount,
  createAccount,
  deleteAccount,
  recoverAccount,
  changePassword,
  characterList,
  createCharacter,
  deleteCharacter,
  selectCharacter,
  moveCharacter,
  teleportCharacter,
  chatMessage,
}
